### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by andreipet** [augustl/path-travel-agent#1]
Hello.
What is the status for publishing in maven central?
Looks nice. And the assumption seems right.
I think building reverse routing will be easier and safer also.

**Comment by augustl** [comment]
Hey there. Thanks for showing interest in the project :)

The "rite of passage" for this project is successful integration into another framework. There's a PR in progress for Spark at https://github.com/perwendel/spark/pull/149 so my plan is to iron out any issues there, and when the Spark peeps are happy, then Path Travel Agent 0.1.0 can be published to maven central.

But if you want it to be in maven central now, I have no problem pushing 0.1.0 at the current state of affairs, and then just bumping to 0.2.0 if the Spark integration requires API changes.

Just let me know :)

**Comment by augustl** [comment]
The spark project did not want to integrate, it seems, they want to be without dependencies so they can manage all the code themselves.

I'll be looking for another project to integrate with. I don't want to release 0.1.0 until path-travel-agent has proven to actually be usable by someone :)

**Comment by andreipet** [comment]
Hello.
If you find such a project please tell me.
Maybe we can convince him to add a spark base class for managing routes,
and spark to first try and see if such an implementation is registered in.
So, spark will not depend on your library.
But I think we will have to come with such an base class. So the impact on
spark will be minimal and everything will work as before for people already
using spark.
I have to work a little bit more with spark to fully understand it's core.
Speaking on dependencies, spark it's tightly bound to jetty even if it can
run in tomcat so it should be split in 2:
spark-core and spark-server.
Keep up the good work and keep in touch. :)

**Comment by augustl** [comment]
Closing this issue - com.augustl.pathtravelagent:0.1.0 is deployed to https://oss.sonatype.org/ now, specifically https://oss.sonatype.org/content/repositories/releases/. First time deploying to maven central, so hopefully everything is working as it should. Let me know if there are any problems!

/cc @akamensky
