### ISSUE TITLE
Maven info

### ISSUE THREAD

**Issue by andreipet** [augustl/path-travel-agent#6]
Hello.
I've start using netty because everything else is corrupt on async io handling or unsafe on thread switching (nio thread and non nio thread (even undertow)).
But netty is so low level that I need a route handler. And I remember talking to you :)
First problem :)
<artifactId>path-travel-agent</artifactId> should be <artifactId>pathtravelagent</artifactId>

**Comment by augustl** [comment]
Thanks for the heads up, fixed :)

I'd love to help out writing something that sits on top of netty. I only provide the raw path matching, but if there's anything I can do to make that easier, let me know.

**Comment by andreipet** [comment]
Ty. I have a few ideas.But I want to collect more info before sending them
to you.
