### ISSUE TITLE
Provide real-world performance benchmark

### ISSUE THREAD

**Issue by tipsy** [augustl/path-travel-agent#9]
Someone just pointed out that Spark should use your path matching technique, which made me check out your project. I'm having some trouble seeing what kind of impact this would have though, could you provide some benchmarks showing the average time it takes to match one route given different amounts of registered routes?

| &#35; Registered routes | Avg. time (PTA) | Avg. time (Spark) |
| --- | --- | --- |
| 1 | x | x |
| 10 | x | x |
| 100 | x | x |
| 1000 | x | x |

**Comment by augustl** [comment]
Hey!

I have a small benchmark set up here:

https://github.com/augustl/path-travel-agent/blob/ffe911e8cdb8eefa6ff0a706642dffc8d4a8ed75/src/test/java/com/augustl/pathtravelagent/PathTravelAgentBenchmark.java

This specifically compares PTA and spark so it should be exactly what you
need.

Here's some example output from that benchmark:

PathTravelAgentBenchmark.largeRouter: [measured 10 out of 15 rounds,
threads: 1 (sequential)]
 round: 0.04 [+- 0.01], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], \
 GC.calls: 2, GC.time: 0.02, time.total: 0.74, time.warmup: 0.37,
time.bench: 0.37

PathTravelAgentBenchmark.sparkRouter: [measured 10 out of 15 rounds,
threads: 1 (sequential)]
 round: 0.66 [+- 0.03], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], \
 GC.calls: 11, GC.time: 0.02, time.total: 10.30, time.warmup: 3.72,
time.bench: 6.58

Let me know if there's anything I can do to help!

**Comment by tipsy** [comment]
Thanks, let's see if I'm reading this right: You have 25 routes mapped, and you're doing 50k requests. You end up with 0.37s and 6.58s. So, PTA matches in ~7 microseconds, while Spark matches in ~130 microseconds?

| &#35; Registered routes | Avg. match time (PTA) | Avg. match time (Spark) |
| --- | --- | --- |
| 25 | ~7 microseconds | ~130 microseconds |

Is this correct?

**Comment by augustl** [comment]
Yup, the math checks out :)

Note that the benchmark is a worst case scenario for Spark when comparing it to a tree structure based route matcher, as the benchmark contains lots of nested routes - /foo, /foo/:id, /foo/:id/bar, etc.

**Comment by tipsy** [comment]
While undoubtedly more efficient than the route matching in Spark, I'm not sure if it's worth the implementation cost for us. Thanks for your help :)

**Comment by augustl** [comment]
You definitely need a pretty intense combination of large number of routes and huge traffic volume for this to matter.

**Comment by tipsy** [comment]
Yup, that was my conclusion too :)
